[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[window]
decorations = "None"
dynamic_title = true

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

